name: dart_vlc_example
description: Demonstrates how to use the dart_vlc plugin.
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_vlc:
    path: ../
  flutter:
    sdk: flutter
dev_dependencies:
  zoo_lints: ^1.0.2
dependency_overrides:
  cupertino_icons: ^1.0.2
  dart_vlc_ffi:
    path: ../ffi
  dart_vlc:
    path: ../

flutter:
  uses-material-design: true
